apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: to-do-app
  namespace: to-do-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: to-do-app
  template:
    metadata:
      labels:
        app: to-do-app
    spec:
      containers:
      - name: to-do-app
        image: 230273005112.dkr.ecr.ap-south-1.amazonaws.com/team_3-to-do:integration
        imagePullPolicy: Always
        ports:
        - name: nginx-port
          containerPort: 80

        livenessProbe:
          httpGet:
            path: /
            port: nginx-port
        readinessProbe:
          httpGet:
            path: /
            port: nginx-port
      
